site_name: LoopLink PRO Help
pages:
- 'index.md'
- Account Management : 'accounts.md'
- Project List : 'project_list.md'
- 'project.md'
- Zone Group : 'zone_group.md'
- 'zone.md'
- Detailed Equipment Selection : 'operating_conditions.md'
- Hot Water Systems : 'hot_water.md'
- Vertically Bored GHEX : 'vb_ghex.md'
- Horizontally Bored GHEX : 'hb_ghex.md'
- SDSU-RR Header Design : 'header.md'

theme: readthedocs
theme_dir: 'custom_theme'